backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Textos do Site"
    files:
      - file: "content/site.json"
        label: "Geral"
        name: "geral"
        fields:
          - { label: "Título (Hero)", name: "heroTitle", widget: "string" }
          - { label: "Subtítulo (Hero)", name: "heroSubtitle", widget: "string" }
          - { label: "Sobre mim", name: "aboutText", widget: "text" }

  - name: "hero"
    label: "Fotos do Hero"
    files:
      - file: "content/hero.json"
        label: "Slideshow"
        name: "slideshow"
        fields:
          - label: "Imagens"
            name: "images"
            widget: "list"
            field: { label: "Imagem", name: "image", widget: "image" }
